name: Build WASI packages
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [jq, rg-p1, rg-p2]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v21
      - run: nix build .#checks.x86_64-linux.${{ matrix.package }} -L
      - run: nix build .#${{ matrix.package }} -o result-package
      - run: nix build .#${{ matrix.package }}-oci -o result-oci
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}-wasi
          path: |
            result-package/bin/*.wasm
            result-package/share/licenses/
      - run: tar -chf ${{ matrix.package }}-oci.tar -C result-oci .
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}-oci
          path: ${{ matrix.package }}-oci.tar
